package newfuzzylogic;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Ammar ALwaeli
 */
public class EncryptionFrame extends javax.swing.JFrame {

    /**
     * Creates new form EncryptionFrame
     */
    ArrayList<Integer> RandomKey;
    ArrayList<Character> letters;
    ArrayList<Integer> asci;
    ArrayList<String> binary;
    String state, key;
    Encryption enc;
    String n = null;
    private Scanner in;
    File file;
    int nmbr;
    private String line;
    boolean saved;

    public void setLetters(ArrayList<Character> letters) {
        //letters.clear();
        this.letters = letters;
    }

    public void setBinary(ArrayList<String> binary) {
        this.binary = binary;
        for (int i = 0; i < letters.size(); i++) {
            jTextArea1.setText(jTextArea1.getText() + binary.get(i));
            jTextArea4.setText(jTextArea4.getText() + letters.get(i));
        }
    }

    public void setASCII(ArrayList<Integer> asci) {
        this.asci = asci;
    }


    public void setEncryption(Encryption e) {
        this.enc = e;
    }

    public EncryptionFrame() {
        initComponents();
        nmbr=130;
        RandomKey = new ArrayList<>();
        letters = new ArrayList<>();
        saved = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        XOR = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        GetRandKey = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        FuzzyKey = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        Back1 = new javax.swing.JButton();
        Save1 = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        Save = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(830, 650));
        setSize(new java.awt.Dimension(830, 670));
        getContentPane().setLayout(null);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Cipher Text"));
        jPanel3.setOpaque(false);

        jTextArea3.setEditable(false);
        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane4.setViewportView(jTextArea3);

        jLabel7.setText("Binary Code XOR Random Key");

        XOR.setText("XOR");
        XOR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                XORMouseClicked(evt);
            }
        });

        jLabel9.setText("Binary Code XOR Random Key (Text)");

        jTextArea6.setEditable(false);
        jTextArea6.setColumns(20);
        jTextArea6.setRows(5);
        jScrollPane6.setViewportView(jTextArea6);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(42, 42, 42)
                        .addComponent(XOR))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(XOR)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6)))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(10, 370, 800, 159);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Random Code Generator"));
        jPanel2.setOpaque(false);

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        jLabel4.setText("Random Key");

        jLabel6.setText("Random Ket (ASCII)");

        GetRandKey.setText("Generate Random Key");
        GetRandKey.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GetRandKeyMouseClicked(evt);
            }
        });

        jTextArea5.setEditable(false);
        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jScrollPane5.setViewportView(jTextArea5);

        FuzzyKey.setText("Fuzzy Key");
        FuzzyKey.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FuzzyKeyMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(GetRandKey))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(FuzzyKey))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(212, 212, 212)
                                .addComponent(jLabel6)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GetRandKey)
                    .addComponent(FuzzyKey))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane5))
                .addContainerGap())
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 170, 800, 193);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Plain Text"));
        jPanel1.setOpaque(false);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jLabel2.setText("Binary Code");

        jLabel3.setText("Plain Text");

        jTextArea4.setEditable(false);
        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane1.setViewportView(jTextArea4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 800, 150);

        Back1.setText("Exit");
        Back1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Back1MouseClicked(evt);
            }
        });
        getContentPane().add(Back1);
        Back1.setBounds(690, 560, 120, 40);

        Save1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Save1.setText("Delete File");
        Save1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Save1MouseClicked(evt);
            }
        });
        getContentPane().add(Save1);
        Save1.setBounds(330, 550, 170, 50);

        Back.setText("Back");
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
        });
        getContentPane().add(Back);
        Back.setBounds(20, 560, 120, 40);

        Save.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Save.setText("Save");
        Save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SaveMouseClicked(evt);
            }
        });
        getContentPane().add(Save);
        Save.setBounds(150, 550, 170, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/EncBG.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, -40, 860, 710);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void XORMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XORMouseClicked
        jTextArea3.setText("");
        jTextArea6.setText("");
        String binaryCode = jTextArea1.getText();
        String randomKey = jTextArea2.getText();
        ArrayList<String> bytes = new ArrayList<>();
        char ascii[] = new char[letters.size()];
        String result = "";
        for (int i = 0; i < binaryCode.length(); i++) {
            if (binaryCode.charAt(i) == randomKey.charAt(i)) {
                result += "0";
            } else {
                result += "1";
            }
        }
        jTextArea3.setText(result);
        int x = 0;
        int y = 0;
        for (int i = 0; i < result.length() / 12; i++) {
            bytes.add(result.substring(x, x + 12));
            x += 12;
            //System.out.print(bytes.get(i) + "\n");
            ascii[i] = (char) binaryToDecimal(Long.parseLong(bytes.get(i)));
            jTextArea6.setText(jTextArea6.getText() + ascii[i]);
        }
    }//GEN-LAST:event_XORMouseClicked

    private void GetRandKeyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GetRandKeyMouseClicked

        jTextArea5.setText("");
        RandomKey.clear();
        jTextArea2.setText("");
        String line1 = "", n1 = "";
        String lin = JOptionPane.showInputDialog(this, "Enter keyword please !", "Enter data", JOptionPane.DEFAULT_OPTION);
        if (lin != null) {
            Number r = new Number(lin);
            for (int i = 0; i < letters.size(); i++) {
                RandomKey.add(r.random(nmbr));
                /*while (RandomKey.get(i) == 0){
                RandomKey.remove(i);
                RandomKey.add(r.random(150));
            }*/
                jTextArea5.setText(jTextArea5.getText() + RandomKey.get(i) + " ");
                line1 = Integer.toBinaryString(RandomKey.get(i));
                if (line1.length() < 12) {
                    for (int j = 0; j < 12 - line1.length(); j++) {
                        n1 += "0";
                    }
                    n1 += line1;
                    jTextArea2.setText(jTextArea2.getText() + n1);
                    //System.out.print(n1 + "\n");
                } else {
                    jTextArea2.setText(jTextArea2.getText() + line1);
                }

                n1 = "";
                line1 = "";
            }
        }
    }//GEN-LAST:event_GetRandKeyMouseClicked

    private void FuzzyKeyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FuzzyKeyMouseClicked
        int s, m, l, sum = 0, div;
        jTextArea5.setText("");
        RandomKey.clear();
        jTextArea2.setText("");
        String line1 = "", n1 = "";
        String lin = JOptionPane.showInputDialog(this, "Enter keyword please !", "Enter data", JOptionPane.DEFAULT_OPTION);
        if (lin != null) {
            Number r = new Number(lin);
            for (int i = 0; i < letters.size(); i++) {
                RandomKey.add(r.random(nmbr));
                sum += RandomKey.get(i);
                
            }
            
            div = sum / RandomKey.size();
            s = (RandomKey.size() * 3) / 2;
            m = (RandomKey.size() * 3) / 2 + s;
            l = (RandomKey.size() * 3) / 2 + (s * 2);

            if (s + m < 100) {
                s = s + m;
                m = m + s;
            } else if (s + m > 100 && s + m < 200) {
                m = Math.abs(m - s);
                s = Math.abs(s - m);
            } else {
                s = (int) (Math.pow(s, 2));
                m = (int) (Math.pow(m, 2));
                l = (int) (Math.pow(l, 2));
            }
            jTextArea5.setText(div + "   Length:" + letters.size());
            for (Character letter : letters) {

                line1 = Integer.toBinaryString(div);
                if (line1.length() < 12) {
                    for (int j = 0; j < 12 - line1.length(); j++) {
                        n1 += "0";
                    }
                    n1 += line1;
                    jTextArea2.setText(jTextArea2.getText() + n1);
                    //System.out.print(n1 + "\n");
                } else {
                    jTextArea2.setText(jTextArea2.getText() + line1);
                }

                n1 = "";
                line1 = "";
            }
        }


    }//GEN-LAST:event_FuzzyKeyMouseClicked

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
        enc.setVisible(true);
    }//GEN-LAST:event_BackMouseClicked

    private void SaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveMouseClicked
        String keyPath = null;
        JFileChooser choser = new JFileChooser();
        int o = choser.showSaveDialog(this);
        if (o != JFileChooser.APPROVE_OPTION) {
            JOptionPane.showMessageDialog(this, "NO Path Selected.");
        } else {
            n = choser.getSelectedFile().getAbsolutePath();
            FileWriter fw = null;
            try {
                File f = null;
                f = new File(n + ".txt");
                fw = new FileWriter(f);
                fw.write(jTextArea6.getText());
                fw.close();
                f.setReadOnly();
                saved = true;
            } catch (IOException e) {
                JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                //System.exit(0);
            }
        }
    }//GEN-LAST:event_SaveMouseClicked

    private void Save1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Save1MouseClicked
        File selectedFile;
        Scanner input;
        String line1;
        JFileChooser loadEmp = new JFileChooser();
        if (loadEmp.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            selectedFile = loadEmp.getSelectedFile();
            if (selectedFile.canRead() && selectedFile.exists()) {
                if (JOptionPane.showConfirmDialog(this, "Do you want to delete this file?", "Submit", JOptionPane.WARNING_MESSAGE) == 0) {
                    line1 = selectedFile.getName();
                    System.out.print(line1 + "\n");
                    selectedFile.delete();
                    selectedFile = new File(new File("").getAbsolutePath() + "\\key " + line1);
                    selectedFile.delete();
                }
            }
        }
    }//GEN-LAST:event_Save1MouseClicked

    private void Back1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Back1MouseClicked
        if (saved) {
            System.exit(0);
        } else {
            if (JOptionPane.showConfirmDialog(this, "Do you want to exit without saving your encryption message?", "Confirm", JOptionPane.YES_NO_OPTION) == 0) {
                System.exit(0);
            }
        }

    }//GEN-LAST:event_Back1MouseClicked

    public String[] split(String s) {
        return s.split(" ");
    }

    public void loadFile(String fileName) throws IOException {
        String line1 = "";
        try {
            File selectedFile = new File(new File("").getAbsolutePath() + "\\key" + fileName);
            if (selectedFile.canRead() && selectedFile.exists()) {
                in = new Scanner(selectedFile);
                while (in.hasNext()) {
                    line1 += in.nextLine();
                }
                key = line1;
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    public static long binaryToDecimal(long binaryNumber) {
        //System.out.print("Enter the binary number : ");
        long d = binaryNumber;
        int c;
        for (c = 0; d != 0; c++) {
            d /= 10;
        }
        long e = binaryNumber;
        long N[];
        N = new long[c];
        for (int i = 0; i < c; i++) {
            N[i] = e % 10;
            e /= 10;
        }
        boolean w = true;
        for (int i = 0; i < N.length; i++) {
            if (N[i] != 1 && N[i] != 0) {
                w = false;
            }
        }
        int b = 0;
        if (w) {
            for (int i = 0; i < N.length; i++) {
                b = (int) (b + (N[i] * Math.pow(2, i)));
            }
            //System.out.print(binaryNumber+" = "+b+"\n");
            return b;
        } else {
            return -1;
        }
        //System.out.print("The number is not binary \n");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EncryptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new EncryptionFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Back1;
    private javax.swing.JButton FuzzyKey;
    private javax.swing.JButton GetRandKey;
    private javax.swing.JButton Save;
    private javax.swing.JButton Save1;
    private javax.swing.JButton XOR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    // End of variables declaration//GEN-END:variables
}
